version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soccer-simulator
    environment:
      - PORT=${PORT}
    ports:
      - '8080:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres
    container_name: soccer-simulator-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
